default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admindb
  password: movies@2023
  host: localhost

development:
  <<: *default
  database: movies

test:
  <<: *default
  database: movies_test

production:
  <<: *default
  database: movies_production
